### ISSUE TITLE
Please add the label "maintained"

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zope.server#30]
@icemac

**Comment by icemac** [comment]
@jugmac00  Do you volunteer to keep this package alive, see #16 for the upcoming problem in 3.12.

**Comment by jugmac00** [comment]
@icemac Thanks a lot for making me aware of the issue.

We checked where we use `zope.server` and it turned out it we were able to remove our dependency on it.

From my side... let it rest in peace :-)

**Comment by icemac** [comment]
I removed the `maintained` topic.
